# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/fadi/Desktop/FluxLang

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/fadi/Desktop/FluxLang

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/opt/homebrew/bin/ctest $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/fadi/Desktop/FluxLang/CMakeFiles /Users/fadi/Desktop/FluxLang//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/fadi/Desktop/FluxLang/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named flux_lexer

# Build rule for target.
flux_lexer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 flux_lexer
.PHONY : flux_lexer

# fast build rule for target.
flux_lexer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flux_lexer.dir/build.make CMakeFiles/flux_lexer.dir/build
.PHONY : flux_lexer/fast

#=============================================================================
# Target rules for targets named flux_scanner_tests

# Build rule for target.
flux_scanner_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 flux_scanner_tests
.PHONY : flux_scanner_tests

# fast build rule for target.
flux_scanner_tests/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/flux_scanner_tests.dir/build.make tests/CMakeFiles/flux_scanner_tests.dir/build
.PHONY : flux_scanner_tests/fast

#=============================================================================
# Target rules for targets named flux_allocator_tests

# Build rule for target.
flux_allocator_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 flux_allocator_tests
.PHONY : flux_allocator_tests

# fast build rule for target.
flux_allocator_tests/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/flux_allocator_tests.dir/build.make tests/CMakeFiles/flux_allocator_tests.dir/build
.PHONY : flux_allocator_tests/fast

src/lexer/scanner.o: src/lexer/scanner.cpp.o
.PHONY : src/lexer/scanner.o

# target to build an object file
src/lexer/scanner.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flux_lexer.dir/build.make CMakeFiles/flux_lexer.dir/src/lexer/scanner.cpp.o
.PHONY : src/lexer/scanner.cpp.o

src/lexer/scanner.i: src/lexer/scanner.cpp.i
.PHONY : src/lexer/scanner.i

# target to preprocess a source file
src/lexer/scanner.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flux_lexer.dir/build.make CMakeFiles/flux_lexer.dir/src/lexer/scanner.cpp.i
.PHONY : src/lexer/scanner.cpp.i

src/lexer/scanner.s: src/lexer/scanner.cpp.s
.PHONY : src/lexer/scanner.s

# target to generate assembly for a file
src/lexer/scanner.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flux_lexer.dir/build.make CMakeFiles/flux_lexer.dir/src/lexer/scanner.cpp.s
.PHONY : src/lexer/scanner.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... flux_allocator_tests"
	@echo "... flux_lexer"
	@echo "... flux_scanner_tests"
	@echo "... src/lexer/scanner.o"
	@echo "... src/lexer/scanner.i"
	@echo "... src/lexer/scanner.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

